### ISSUE TITLE
Tried to use it with blender 3.6.1 but it errs

### ISSUE THREAD

**Issue by BrahRah** [belzecue/ReSprytile#1]
Here is the log:

```
Traceback (most recent call last):
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_modal.py", line 608, in modal
    self.exit_modal(event, context)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_modal.py", line 924, in exit_modal
    self.call_tool(event, False, context)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_modal.py", line 712, in call_tool
    build_preview=self.draw_preview,
  File "/home/r2d2/MyApps/blender-3.6.1-linux-x64/3.6/scripts/modules/bpy_types.py", line 855, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OP_SprytileModalTool' object has no attribute 'draw_preview'
Error: Python: Traceback (most recent call last):
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_modal.py", line 608, in modal
    self.exit_modal(event, context)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_modal.py", line 924, in exit_modal
    self.call_tool(event, False, context)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_modal.py", line 712, in call_tool
    build_preview=self.draw_preview,
  File "/home/r2d2/MyApps/blender-3.6.1-linux-x64/3.6/scripts/modules/bpy_types.py", line 855, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OP_SprytileModalTool' object has no attribute 'draw_preview'
```

**Comment by BrahRah** [comment]
I get the exact same error in 3.41 too.

After loading the spritesheet and clicking on a tile via Build brush:
```
Traceback (most recent call last):
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_gui.py", line 205, in modal
    ret_val = self.handle_ui(context, event)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_gui.py", line 489, in handle_ui
    tilegrid.tile_selection[0] = sel_min.x
TypeError: expected an int type
Error: Python: Traceback (most recent call last):
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_gui.py", line 205, in modal
    ret_val = self.handle_ui(context, event)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_gui.py", line 489, in handle_ui
    tilegrid.tile_selection[0] = sel_min.x
TypeError: expected an int type
```
The first error happens when then clicking on the cube mesh via the Build brush.

**Comment by BrahRah** [comment]
I found the first issue (sprytile_gui.py): 
```           if VIEW3D_OP_SprytileGui.is_selecting:
                sel_min = Vector((
                    min(grid_pos.x, VIEW3D_OP_SprytileGui.sel_start.x),
                    min(grid_pos.y, VIEW3D_OP_SprytileGui.sel_start.y)
                ))
                sel_max = Vector((
                    max(grid_pos.x, VIEW3D_OP_SprytileGui.sel_start.x),
                    max(grid_pos.y, VIEW3D_OP_SprytileGui.sel_start.y)
                ))

                tilegrid.tile_selection[0] = sel_min.x
                tilegrid.tile_selection[1] = sel_min.y
                tilegrid.tile_selection[2] = (sel_max.x - sel_min.x) + 1
                tilegrid.tile_selection[3] = (sel_max.y - sel_min.y) + 1
 ```
sel_min and sell_max have float values for some reason like: <Vector (25.0000, 16.0000)>
So I just changed it to:
```            tilegrid.tile_selection[0] = int(sel_min.x)
                tilegrid.tile_selection[1] = int(sel_min.y)
                tilegrid.tile_selection[2] = (int(sel_max.x) - int(sel_min.x)) + 1
                tilegrid.tile_selection[3] = (int(sel_max.y) - int(sel_min.y)) + 1
``` 
That seems to work for the 2nd error. But the first `object has no attribute 'draw_preview'` is still there.

**Comment by BrahRah** [comment]
Wow I did not expect to be able to fix the issue but since the zoom on the spritesheet preview also had a float issue I did:
```
        context.scene.sprytile_ui.palette_pos[0] = int(display_offset.x)
        context.scene.sprytile_ui.palette_pos[1] = int(display_offset.y)
```
in the sprytile_gui.py and that seems to have fixed the 'draw_preview' issue too.

**Comment by BrahRah** [comment]
There are some issues with the preview vanishing when using the middle mouse button to rotate the view tho.

**Comment by belzecue** [comment]
@BrahRah, great job hunting down that bug 👍.  This is an inactive fork, sorry, but you can open an issue with https://github.com/ionthedev/ReSprytile and you'll likely get some help there.
